In [13]:
import numpy as np

X1 = np.array([[0, 2], [1, 1], [2, 0]]).T
x = [-2.1, -1,  4.3]
y = [3,  1.1,  0.12]
X2 = np.stack((x, y), axis=0)

X3  = np.array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])
       
X4 = np.array([[0.45038594, 0.37079802, 0.92676499],
       [0.64386512, 0.82276161, 0.4434142 ],
       [0.22723872, 0.55458479, 0.06381726]])

In [14]:
def my_cov(m):
    means = np.mean(m, axis=1)
    sub_mean = m - means[:, None]
    prod = sub_mean@sub_mean.T
    prod_norm = prod / (m.shape[1]-1)
    return prod_norm

def my_corrcoef(m):
    C = my_cov(m)
    diag = np.diag(C)[:, None]
    denom = np.sqrt(diag@diag.T)
    corrcoef = np.divide(C, denom)
    return corrcoef

In [15]:
print(f"Numpy cov(): \n {np.cov(X1)}")
print(f"My cov(): \n {my_cov(X1)}")

print(f"Numpy cov(): \n {np.cov(X2)}")
print(f"My cov(): \n {my_cov(X2)}")

print(f"Numpy corrcoef(): \n {np.corrcoef(X3)}")
print(f"My corrcoef(): \n {my_corrcoef(X3)}")

print(f"Numpy corrcoef(): \n {np.corrcoef(X4)}")
print(f"My corrcoef(): \n {my_corrcoef(X4)}")

Numpy cov(): 
 [[ 1. -1.]
 [-1.  1.]]
My cov(): 
 [[ 1. -1.]
 [-1.  1.]]
Numpy cov(): 
 [[11.71       -4.286     ]
 [-4.286       2.14413333]]
My cov(): 
 [[11.71       -4.286     ]
 [-4.286       2.14413333]]
Numpy corrcoef(): 
 [[ 1.          0.99256089 -0.68080987]
 [ 0.99256089  1.         -0.76492173]
 [-0.68080987 -0.76492173  1.        ]]
My corrcoef(): 
 [[ 1.          0.99256089 -0.68080987]
 [ 0.99256089  1.         -0.76492173]
 [-0.68080987 -0.76492173  1.        ]]
Numpy corrcoef(): 
 [[ 1.         -0.93657855 -0.83571711]
 [-0.93657855  1.          0.97517215]
 [-0.83571711  0.97517215  1.        ]]
My corrcoef(): 
 [[ 1.         -0.93657855 -0.83571711]
 [-0.93657855  1.          0.97517215]
 [-0.83571711  0.97517215  1.        ]]


In [16]:
X1

array([[0, 1, 2],
       [2, 1, 0]])